### ISSUE TITLE
SwiftLint を導入してみる

### ISSUE THREAD

**Issue by konomae** [IwanagaSari/GitHubApp1#4]
SwiftLint などの書式使って、コードの書式を整えると良さそうです
インデントとかの細かいやつは `swiftlint autocorrect` などとコマンドを打つといい感じに整えてくれるので

**Comment by MurakiSari** [comment]
Homebrewインストール、SwiftLintをインストール、Build PhasesのRub Scriptにswiftlint autocorrectを追記してみた。.swiftlint.ymlファイルの作り方がよくわからない。

**Comment by konomae** [comment]
> Homebrewインストール、SwiftLintをインストール

🙆‍♂️👍

.swiftlint.yml の作成はコマンドラインでもできるんですが Visual Studio Code とかの汎用的なエディタを入れてもいいかなと思いました。

あと、swiftlint で警告をだす程度にとどめると良さそうに思いました。
swiftlint autocorrect だとフォーマットがうまくいかずに予期せずコードが壊れないとも限らないので。

**Comment by MurakiSari** [comment]
swiftlint を導入し、たくさんのエラーと警告が表示されるようになった。
 Visual Studio Codeで.swiftlint.ymlを作成し、少しエラーと警告が減った。

エラーや警告が表示されていてもビルドして実行されていたが、Build PhasesのRub Scriptからswiftlint autocorrect を消すと、実行されなくなってしまうので、とりあえずswiftlint autocorrectはそのまま追記したままにしてます。。

**Comment by konomae** [comment]
導入はしたと思うのでクローズしちゃいます
