### ISSUE TITLE
APIのエラー処理を行う

### ISSUE THREAD

**Issue by konomae** [IwanagaSari/GitHubApp1#6]
- HTTP のエラー処理を行う (status code などを見る)
- GitHub の API のエラー処理を行う (トークンが有効でない場合などに返ってくるエラー)

**Comment by konomae** [comment]
APIがエラー情報を返してくれている (例えば、レートリミットに引っかかった時とか)
そのレスポンスの中にエラーメッセージが入っているので、そのエラーを取り出したい。

現状だと、APIがエラーかどうかに関わらずJSON をデコードしようとしているので、
JSONデコードのエラーにはなるが、本来のAPIのエラーが何かわからなくなっている

**Comment by MurakiSari** [comment]
status codeを表示されるように実装。
print("response.statusCode = \(response.statusCode)")

とりあえず、
let task: URLSessionTask = URLSession.shared.dataTask(with: req, completionHandler: {data, response, error in　の後に
print(response)と追記したら、レスポンスの内容が色々表示されるようになったが（status codeやrate limitなど）、そのどれかがエラーメッセージを表示するようになっているでしょうか？
